site:
  title: title of my doc
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://github.com/acampergue-camptocamp/minitedtalk
  start_page: my_doc::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    edit_url: false
    start_path: docs
  - url: https://github.com/camptocamp/camptocamp-devops-stack
    branches: master
    tags: [v0.4.1,v0.5.1]
    edit_url: false
    start_path: docs
ui:
  bundle:
    ## Use the default Antora UI
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    ## Use camptocamp's UI bundle
    url: https://github.com/camptocamp/antora-ui/releases/download/LATEST/ui-bundle.zip
    ## Use a modified version of camptocamp's UI with dark theme for local tests without burning my eyes
    #url: https://github.com/acampergue-camptocamp/antora-ui/releases/download/LATEST/ui-bundle.zip
    ## Or even steal the UI from other project
    #url: https://github.com/aerogear/antora-ui/raw/master/build/ui-bundle.zip
    #url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true
  supplemental_files:
  # Special setup to disable jekyll from github which messes up with the Theme of the resulting website
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll